/*
 *
 * Layout constants
 *
 */

export const CHANGE_SIDEBAR_VISIBILITY = 'app/layout/CHANGE_SIDEBAR_VISIBILITY';
export const CHANGE_MOBILE_SIDEBAR_VISIBILITY = 'app/layout/CHANGE_MOBILE_SIDEBAR_VISIBILITY';

export const ON_USERPROFILE_LOAD = 'app/ProfilePage/ON_USERPROFILE_LOAD';
export const ON_USERPROFILE_LOAD_SUCCESS = 'app/ProfilePage/ON_USERPROFILE_LOAD_SUCCESS';
export const ON_USERPROFILE_LOAD_FAILED = 'app/ProfilePage/ON_USERPROFILE_LOAD_FAILED';

export const CHANGE_SIDENAV_SELECTED = 'app/layout/CHANGE_SIDENAV_SELECTED';
