/*
 *
 * Layout constants
 *
 */

export const CHANGE_SIDEBAR_VISIBILITY = 'app/layout/CHANGE_SIDEBAR_VISIBILITY';
export const CHANGE_MOBILE_SIDEBAR_VISIBILITY =
  'app/layout/CHANGE_MOBILE_SIDEBAR_VISIBILITY';

export const CHANGE_SIDENAV_SELECTED =
  'app/layout/CHANGE_SIDENAV_SELECTED';
