export const ON_PROFILEPAGE_LOAD = 'app/ProfilePage/ON_PROFILEPAGE_LOAD';
export const ON_PROFILEPAGE_LOAD_SUCCESS = 'app/ProfilePage/ON_PROFILEPAGE_LOAD_SUCCESS';
export const ON_PROFILEPAGE_LOAD_FAILED = 'app/ProfilePage/ON_PROFILEPAGE_LOAD_FAILED';

export const ON_PROFILEPAGE_SAVE = 'app/ProfilePage/ON_PROFILEPAGE_SAVE';
export const ON_PROFILEPAGE_SAVE_SUCCESS = 'app/ProfilePage/ON_PROFILEPAGE_SAVE_SUCCESS';
export const ON_PROFILEPAGE_SAVE_FAILED = 'app/ProfilePage/ON_PROFILEPAGE_SAVE_FAILED';

export const ON_PROFILE_EDIT = 'app/ProfilePage/ON_PROFILE_EDIT';
export const ON_PROFILE_EDIT_SUCCESS = 'app/ProfilePage/ON_PROFILE_EDIT_SUCCESS';
export const ON_PROFILE_EDIT_FAILED = 'app/ProfilePage/ON_PROFILE_EDIT_FAILED';

export const ON_USERPROFILE_DELETE = 'app/ProfilePage/ON_USERPROFILE_DELETE';
export const ON_USERPROFILE_DELETE_SUCCESS = 'app/ProfilePage/ON_USERPROFILE_DELETE_SUCCESS';
export const ON_USERPROFILE_DELETE_FAILED = 'app/ProfilePage/ON_PROFILE_EDIT_FAILED';
