export const ON_PROFILEPAGE_LOAD = 'app/ResourcePage/ON_PROFILEPAGE_LOAD';
export const ON_PROFILEPAGE_LOAD_SUCCESS = 'app/ResourcePage/ON_PROFILEPAGE_LOAD_SUCCESS';
export const ON_PROFILEPAGE_LOAD_FAILED = 'app/ResourcePage/ON_PROFILEPAGE_LOAD_FAILED';

export const ON_PROFILEPAGE_SAVE = 'app/ResourcePage/ON_PROFILEPAGE_SAVE';
export const ON_PROFILEPAGE_SAVE_SUCCESS = 'app/ResourcePage/ON_PROFILEPAGE_SAVE_SUCCESS';
export const ON_PROFILEPAGE_SAVE_FAILED = 'app/ResourcePage/ON_PROFILEPAGE_SAVE_FAILED';

export const ON_PROFILE_EDIT = 'app/ResourcePage/ON_PROFILE_EDIT';
export const ON_PROFILE_EDIT_SUCCESS = 'app/ResourcePage/ON_PROFILE_EDIT_SUCCESS';
export const ON_PROFILE_EDIT_FAILED = 'app/ResourcePage/ON_PROFILE_EDIT_FAILED';
